import { useState, useEffect } from 'react';
import api from '../utils/api';
import { useAuth } from '../context/AuthContext';
import jsPDF from "jspdf";
import html2canvas from "html2canvas";


const Documents = () => {
  const { user } = useAuth();
  const [documents, setDocuments] = useState([]);
  const [patients, setPatients] = useState([]);
  const [loading, setLoading] = useState(true);
  const [showModal, setShowModal] = useState(false);
  const [formData, setFormData] = useState({
    patient: '', title: '', description: '', category: 'Other', file: null
  });

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    try {
      setLoading(true);
      const [docsRes, patientsRes] = await Promise.all([
        api.get('/documents'),
        api.get('/patients')
      ]);
      setDocuments(docsRes.data.documents);
      setPatients(patientsRes.data.patients);
    } catch (error) {
      alert('Error fetching data');
       console.error(error);
    } finally {
      setLoading(false);
    }
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    
    if (!formData.file) {
      alert('Please select a file');
      return;
    }

    const data = new FormData();
    data.append('patient', formData.patient);
    data.append('title', formData.title);
    data.append('description', formData.description);
    data.append('category', formData.category);
    data.append('file', formData.file);

    try {
      await api.post('/documents', data, {
        headers: { 'Content-Type': 'multipart/form-data' }
      });
      alert('Document uploaded successfully');
      setShowModal(false);
      resetForm();
      fetchData();
    } catch (error) {
      alert(error.response?.data?.message || 'Error uploading document');
    }
  };

  const handleDownload = (doc) => {
  const element = document.createElement("div");
  element.style.width = "800px";
  element.style.padding = "25px";
  element.style.fontFamily = "'Poppins', sans-serif";

  element.innerHTML = `
    <h1 style="color:#004199;margin-bottom:3px;">Hospital Document Report</h1>
    <p style="font-size:13px;color:#666;margin-top:0;margin-bottom:15px">Generated by HMS System</p>
    <hr style="margin-bottom:20px"/>
    <h2 style="margin-bottom:5px">${doc.title}</h2>
    <p><b>Patient:</b> ${doc.patient?.name ?? 'N/A'}</p>
    <p><b>Category:</b> ${doc.category}</p>
    <p><b>Description:</b> ${doc.description || '-'}</p>
    <p><b>Uploaded By:</b> ${doc.uploadedBy?.name ?? '-'}</p>
    <p><b>Date:</b> ${new Date(doc.createdAt).toLocaleDateString()}</p>
    <hr style="margin-top:25px"/>
    <p style="font-size:10px;color:#777;margin-top:10px">© HMS - generated PDF</p>
  `;

  document.body.appendChild(element);

  html2canvas(element, { scale: 2 }).then(canvas => {
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "pt", "a4");

    const pageWidth = pdf.internal.pageSize.getWidth();
    const imgWidth = pageWidth - 40;
    const imgHeight = (canvas.height * imgWidth) / canvas.width;

    pdf.addImage(imgData, "PNG", 20, 20, imgWidth, imgHeight);
    pdf.save(`${doc.title}.pdf`);
    document.body.removeChild(element);
  })
};

  const handleVerify = async (id) => {
    try {
      await api.patch(`/documents/${id}/verify`);
      alert('Document verified successfully');
      fetchData();
    } catch (error) {
      alert(error.response?.data?.message || 'Error verifying document');
    }
  };

  const handleDelete = async (id) => {
    if (!window.confirm('Are you sure you want to delete this document?')) return;
    try {
      await api.delete(`/documents/${id}`);
      alert('Document deleted successfully');
      fetchData();
    } catch (error) {
      alert('Error deleting document');
       console.error(error);
    }
  };

  const resetForm = () => {
    setFormData({
      patient: '', title: '', description: '', category: 'Other', file: null
    });
  };

  const openModal = () => {
    resetForm();
    setShowModal(true);
  };

  const formatFileSize = (bytes) => {
    return (bytes / 1024).toFixed(2) + ' KB';
  };

  const formatDate = (dateString) => {
    return new Date(dateString).toLocaleDateString();
  };

  return (
    <div className="page-container">
      <div className="page-header">
        <h1>Documents Management</h1>
        {(user?.role === 'doctor' || user?.role === 'admin') && (
          <button className="btn-primary" onClick={openModal}>+ Upload Document</button>
        )}
      </div>

      {loading ? (
        <div className="loading">Loading documents...</div>
      ) : (
        <div className="table-container">
          <table>
            <thead>
              <tr>
                <th>Title</th>
                <th>Patient</th>
                <th>Category</th>
                <th>Uploaded By</th>
                <th>Date</th>
                <th>Size</th>
                <th>Verified</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {documents.length === 0 ? (
                <tr><td colSpan="8" style={{textAlign: 'center'}}>No documents found</td></tr>
              ) : (
                documents.map((doc) => (
                  <tr key={doc._id}>
                    <td>{doc.title}</td>
                    <td>{doc.patient?.name || 'N/A'}</td>
                    <td>{doc.category}</td>
                    <td>{doc.uploadedBy?.name || 'N/A'}</td>
                    <td>{formatDate(doc.createdAt)}</td>
                    <td>{formatFileSize(doc.fileSize)}</td>
                    <td>{doc.isVerified ? '✓ Yes' : '✗ No'}</td>
                    <td>
                     <button className="btn-sm btn-primary" onClick={() => handleDownload(doc)}>Download</button>

                      {user?.role === 'admin' && !doc.isVerified && (
                        <button className="btn-sm btn-success" onClick={() => handleVerify(doc._id)}>Verify</button>
                      )}
                      {(user?.role === 'admin' || doc.uploadedBy?._id === user?.id) && (
                        <button className="btn-sm btn-delete" onClick={() => handleDelete(doc._id)}>Delete</button>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      )}

      {showModal && (
        <div className="modal-overlay" onClick={() => setShowModal(false)}>
          <div className="modal-content" onClick={(e) => e.stopPropagation()}>
            <h2>Upload New Document</h2>
            <form onSubmit={handleSubmit}>
              <div className="form-group">
                <label>Patient *</label>
                <select value={formData.patient} onChange={(e) => setFormData({...formData, patient: e.target.value})} required>
                  <option value="">Select Patient</option>
                  {patients.map(p => <option key={p._id} value={p._id}>{p.name}</option>)}
                </select>
              </div>
              <div className="form-group">
                <label>Title *</label>
                <input type="text" value={formData.title} onChange={(e) => setFormData({...formData, title: e.target.value})} required />
              </div>
              <div className="form-group">
                <label>Category</label>
                <select value={formData.category} onChange={(e) => setFormData({...formData, category: e.target.value})}>
                  <option value="Prescription">Prescription</option>
                  <option value="Medical Report">Medical Report</option>
                  <option value="Test Result">Test Result</option>
                  <option value="X-Ray">X-Ray</option>
                  <option value="Other">Other</option>
                </select>
              </div>
              <div className="form-group">
                <label>Description</label>
                <textarea value={formData.description} onChange={(e) => setFormData({...formData, description: e.target.value})} />
              </div>
              <div className="form-group">
                <label>File * (PDF or Image, max 5MB)</label>
                <input type="file" accept=".pdf,.jpg,.jpeg,.png" onChange={(e) => setFormData({...formData, file: e.target.files[0]})} required />
              </div>
              <div className="modal-actions">
                <button type="button" className="btn-secondary" onClick={() => setShowModal(false)}>Cancel</button>
                <button type="submit" className="btn-primary">Upload</button>
              </div>
            </form>
          </div>
        </div>
      )}
    </div>
  );
};

export default Documents;